### PR TITLE
New version (2.0)

### PR DESCRIPTION
**Pull request by bforest76**
- translation management (and as I'm french I created a onedrive_tray_fr.qm file)
- icon color choice with QColorDialog and a dynamic color icon management
- application settings : saved and loaded (icon color for example)
- a different icon when syncing (cloud with rain)
- show the remaining space on OneDrive
- show the status
- add an about box
- fix an open folder issue
- and many other...

menu_fr
menu_en
about_en
more colors

### CODE REVIEW

**Comment by jugendhacker** [comment]
"New version" is actually a pretty bad commit message, especially if you use it for five different commits. A good commit message should describe what the commit actually does.

**Comment by bforest76** [comment]
> "New version" is actually a pretty bad commit message, especially if you use it for five different commits. A good commit message should describe what the commit actually does.

Sorry about that. I'm a very early user of github (it's my first upload) and don't kown exactly how to manage it fine.

**Comment by jotkah** [comment]
So this version will never be commited because of those "unlucky" commit messages?

**Comment by jugendhacker** [comment]
@jotkah I don't know, I'm not the maintainer, but good commit messages are always useful if you use git and they could in theory easily be changed via rebasing.

**Comment by jugendhacker** [comment]
@bforest76 please take a look on https://github.com/pedrolcl/qt-i18n how to to the translations correctly with qmake, so we would not need to but compiled binaries into git and avoid things like loading translations from the binary dir.

**Comment by bforest76** [comment]
> @bforest76 please take a look on https://github.com/pedrolcl/qt-i18n how to to the translations correctly with qmake, so we would not need to but compiled binaries into git and avoid things like loading translations from the binary dir.

@jugendhacker Thanks a lot for the advice. I will try to do this way.

**Pull request merged**
